version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    ports:
      - '9010:9010'
      - '9011:9011'
    networks:
      - agent_network
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=yCj1Q1DKznby
    command: minio server /data --console-address ":9011"

networks:
  agent_network:
    external: true

volumes:
  minio_data:
    driver: local